// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/quang/.local/react-project/nv-commbook/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/quang/.local/react-project/nv-commbook/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('nv-commbook', appParameters);
});
require('c:/Users/quang/.local/react-project/nv-commbook/index.js');